[project]
name = "llmpretrain"
version = "0.1.0"
requires-python = ">=3.11"
description = "My LLM pretraining project"
authors = [
    { name="Your Name", email="you@example.com" }
]
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
]
